[package]
name = "so-api"
version = "0.1.0"
authors = ["George Aristy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
