name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  UnitTest:
    name: unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup docker
        run: sudo apt update && sudo apt install moby-cli moby-engine containerd.io
      - name: test
        uses: icepuma/rust-action@1.52.1
        with:
          args: make test
  Lint:
    name: linters
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup docker
        run: sudo apt update && sudo apt install moby-cli moby-engine containerd.io
      - name: cargo-lint
        uses: icepuma/rust-action@1.52.1
        with:
          args: make cargo-lint
      - name: docker-lint
        run: make docker-lint
